GET http://localhost:5001/characters/rank

### 

GET http://localhost:5001/users/check
Authorization: Bearer

### 

POST http://localhost:5001/users/signin
Content-Type: application/json

{
  "username": "0strich",
  "password":"1234"
}

###

POST http://localhost:5001/users/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdlZTgxOTZAZ21haWwuY29tIiwicGFzc3dvcmQiOiIxMjM0IiwiaWF0IjoxNTkwODM4Mjk3LCJleHAiOjE1OTQ0MzgyOTd9.RZfBJheCLgdZZdEvqas1OCxB7BK-LDex2e7KVeo6Z4c"
}

###

POST http://localhost:5001/characters/info
Content-Type: application/json

{
  "userId": 1
}
